#cron表达式"分 时 日 月 周"，请参考https://www.runoob.com/linux/linux-comm-crontab.html
users:
  - qmsg:
      qq: "*********" # qq号
      key: ********* # qmsg酱的key
      isgroup: 0 # 类型：1为群，0为个人(不可混用)
    weather:
      citycode: ********* # citycode请在https://github.com/baichengzhou/weather.api/blob/master/src/main/resources/citycode-2019-08-23.json里面找
      cron: "* * * * *" # 天气推送时间
    cronevents_keys: ["routine", "addition"] # 需要推送事件列表的key(见cronevents_table)
cronevents_table: # cron触发事件列表
  routine:
    - title: "测试1" # 标题
      time: "* * * * *" # 使用cron表达式
    - title: "测试2"
      time: "* * * * *"
  addition:
    - title: "测试3"
      time: "* * * * *"
  adddd:
    - title: "测试6"
      time: "* * * * *"
