#time格式为 "%Y %w %m %d %H %M"，*为通配符
trigger:
 qq: 'xxxxxxxxxxx'
 #qmsg酱的key
 key: xxxxxxxxxxxxxxxxxxx
 timetable:
  -
    title: '早安，早上的状态会为一天奠定基调，就算仍有困意，也要强迫自己打起精神来!'
    time: '* * * * 7 0'
  -
    title: '午饭吃了没？'
    time: '* * * * 12 0'
  -
    title: '午安，休息下吧。'
    time: '* * * * 13 0'
  -
    title: '夜幕降临，灯火初上。嗯——又是安宁祥和的一天呢。放下手上的工作准备睡觉吧。'
    time: '* * * * 21 0'
  -
    title: '去休息吧。'
    time: '* * * * 22 30'
  -
    title: '认真工作是不错，不要忘记补充水分'
    time: '* * * * * 0'