#时间使用cron表达式"分 时 日 月 周"，请参考https://www.runoob.com/linux/linux-comm-crontab.html
trigger:
  -
    qmsg:
      qq: '********'
      #qmsg酱的key
      key: '****************'
      #类型：group为群，send为个人
      type: send
    #citycode请在https://github.com/baichengzhou/weather.api/blob/master/src/main/resources/citycode-2019-08-23.json 里面找
    citycode: 101010100
    weathertime: '0 7 * * *'
    timetable:
      # 时间表
      -
        title: '早安，周围的一切都在孕育着美好。'
        time: '0 7 * * *'
      -
        title: '吃早餐是一件很重要的事情，一定要吃得好吃得饱哦。'
        time: '15 7 * * *'  
  # -
  #   qmsg:
  #     qq: '********'
  #     #qmsg酱的key
  #     key: '****************'
  #     #类型：group为群，send为个人
  #     type: send
  #   citycode: 101010100
  #   weathertime: '0 7 * * *'
  #   timetable:
  #     # 早上
  #     -
  #       title: '早安，早上的状态会为一天奠定基调，就算仍有困意，也要强迫自己打起精神来!'
  #       time: '0 7 * * *'
