#time使用cron表达式"分 时 日 月 周"，请参考https://www.runoob.com/linux/linux-comm-crontab.html
trigger:
 qq: '12345'
 #qmsg酱的key
 key: xxxxxxxxxxxxxxxxxxxxxxx
 timetable:
  -
    title: '早安，早上的状态会为一天奠定基调，就算仍有困意，也要强迫自己打起精神来!'
    time: '0 7 * * *'
  -
    title: '午饭吃了没？'
    time: '0 12 * * *'
  -
    title: '午安，休息下吧。'
    time: '0 13 * * *'
  -
    title: '夜幕降临，灯火初上。嗯——又是安宁祥和的一天呢。放下手上的工作准备睡觉吧。'
    time: '0 21 * * *'
  -
    title: '去休息吧。'
    time: '30 22 * * *'
  -
    title: '认真工作是不错，不要忘记补充水分'
    time: '*/30 * 25 1 *'
